sudo: true
language: generic

os: linux
dist: xenial

services:
  - docker

branches:
  only:
    - develop
    - master

before_install:
  - cd ./frontend
  - docker build -t ysidorko/ui-server -f Dockerfile .

#script:
#  - docker run -e CI=true ysidorko/ui-server npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket: "elasticbeanstalk-eu-north-1-099545163540"
  bucket_path: "docker-react"
  on:
    all_branches: true
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
