language: generic

sudo: required
services:
  - docker

env:
  - ENV=dev PLATFORM=cf

dist: xenial

branches:
  only:
    - /^dev-v[0-9|\.]+/

before_install:
  - cd ./frontend
  - docker build -t ysidorko/docker-course -f Dockerfile.dev .

script:
  - docker run -e CI=true ysidorko/ui-server npm run test
