language: generic

sudo: required
services:
  - docker

env:
  - ENV=dev PLATFORM=cf
  - ENV=test PLATFORM=cf

dist: xenial

branches:
  only:
    - /^dev-v[0-9|\.]+/
    - /^test-v[0-9|\.]+/

before_install:
  - docker build -t ysidorko/docker-course -f Dockerfile.dev ./frontend

script:
  - docker run -e CI=true ysidorko/ui-server npm run test
