version: '3'
services:
  redis-server:
    image: 'redis:latest'
  postgres-server:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=P1234567890
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    restart: always
    ports:
      - '3333:80'
    depends_on:
      - api
      - ui
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/api/node_modules
      - ./server:/usr/api
    environment:
      - API_PORT=5000
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres-server
      - PGDATABASE=postgres
      - PGPASSWORD=P1234567890
      - PGPORT=5432
    restart: always
  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/ui/node_modules
      - ./frontend:/usr/ui
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/worker/node_modules
      - ./worker:/usr/worker
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379

#  ui-server:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - '80:80'
#    restart: always
