apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: server
          image: ysidorko/api
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip
            - name: REDIS_PORT
              value: '6379'
            - name: API_PORT
              value: '5000'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: PGPORT
              value: '5432'
